# Generated by Django 4.0.2 on 2022-02-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("link", models.URLField()),
                ("author", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=1000)),
                ("pub_date", models.DateField()),
            ],
        ),
    ]
